name: flow
description: A mobile Twitch client for Android.
version: 1.0.0+1
publish_to: none
repository: https://github.com/namecallfilter/flow

environment:
    sdk: ^3.12.2

dependencies:
    flutter:
        sdk: flutter
    flutter_mobx: ^2.3.0
    flutter_secure_storage: ^10.3.1
    http: ^1.6.0
    mobx: ^2.6.0
    shared_preferences: ^2.5.5
    webview_flutter: ^4.14.0

dev_dependencies:
    build_runner: ^2.15.0
    flutter_lints: ^6.0.0
    flutter_test:
        sdk: flutter
    mobx_codegen: ^2.7.7

flutter:
    uses-material-design: true
