query FlowVodChat($videoId: ID!, $offsetSeconds: Int, $cursor: Cursor) {
  video(id: $videoId) {
    comments(contentOffsetSeconds: $offsetSeconds, after: $cursor) {
      edges {
        cursor
        node {
          id
          contentOffsetSeconds
          commenter {
            id
            login
            displayName
          }
          message {
            fragments {
              text
              emote {
                emoteID
              }
            }
            userBadges {
              setID
              version
            }
            userColor
          }
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
