query FlowSearchChannels(
  $queryFragment: String!
  $requestID: ID
  $withOfflineChannelContent: Boolean
) {
  searchSuggestions(
    queryFragment: $queryFragment
    requestID: $requestID
    withOfflineChannelContent: $withOfflineChannelContent
  ) {
    edges {
      node {
        content {
          __typename
          ... on SearchSuggestionChannel {
            id
            isLive
            isVerified
            login
            profileImageURL(width: 50)
            user {
              id
              isPartner
              stream {
                id
                viewersCount
                createdAt
                game {
                  id
                  displayName
                }
                broadcaster {
                  id
                  broadcastSettings {
                    id
                    title
                  }
                }
              }
            }
          }
        }
        id
        text
      }
    }
  }
}
