query FlowFollowedLiveUsers($first: Int, $after: Cursor) {
  currentUser {
    followedLiveUsers(first: $first, after: $after, sort: RELEVANCE) {
      edges {
        cursor
        node {
          id
          login
          displayName
          profileImageURL(width: 300)
          stream {
            id
            createdAt
            freeformTags {
              name
            }
            game {
              id
              displayName
            }
            previewImageURL
            viewersCount
            broadcaster {
              broadcastSettings {
                title
              }
            }
          }
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
