query FlowChannelDetails($login: String!, $videosFirst: Int, $videosAfter: Cursor) {
  user(login: $login) {
    id
    login
    displayName
    isPartner
    description
    profileImageURL(width: 300)
    followers {
      totalCount
    }
    stream {
      id
      createdAt
      game {
        id
        displayName
        name
      }
      previewImageURL(width: 320, height: 180)
      viewersCount
      broadcaster {
        broadcastSettings {
          title
        }
      }
    }
    videos(first: $videosFirst, after: $videosAfter, sort: TIME, type: ARCHIVE) {
      edges {
        cursor
        node {
          id
          title
          game {
            id
            displayName
            name
          }
          lengthSeconds
          previewThumbnailURL(width: 320, height: 180)
          publishedAt
          createdAt
          viewCount
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
