query FlowUsers($ids: [ID!], $logins: [String!]) {
  users(ids: $ids, logins: $logins) {
    id
    login
    displayName
    isPartner
    profileImageURL(width: 300)
    lastBroadcast {
      startedAt
    }
    broadcastSettings {
      title
      game {
        id
        displayName
      }
    }
    stream {
      id
      createdAt
      freeformTags {
        name
      }
      game {
        id
        displayName
      }
      previewImageURL
      viewersCount
      broadcaster {
        broadcastSettings {
          title
        }
      }
    }
  }
}
