query FlowGameStreams($id: ID, $first: Int, $after: Cursor, $options: GameStreamOptions) {
  game(id: $id) {
    streams(first: $first, after: $after, options: $options) {
      edges {
        cursor
        node {
          id
          broadcaster {
            id
            login
            displayName
            isPartner
            profileImageURL(width: 300)
            broadcastSettings {
              title
            }
          }
          createdAt
          freeformTags {
            name
          }
          game {
            id
            displayName
          }
          previewImageURL
          viewersCount
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}
