query FlowChatReplies($messageID: ID!) {
  message(id: $messageID) {
    ...FlowChatReplyMessage
    replies {
      nodes {
        ...FlowChatReplyMessage
      }
      totalCount
    }
  }
}

fragment FlowChatReplyMessage on Message {
  id
  sentAt
  deletedAt
  sender {
    id
    login
    displayName
  }
  senderChatColor
  senderBadges {
    setID
    version
  }
  content {
    text
    fragments {
      text
      content {
        __typename
        ... on Emote {
          emoteID: id
        }
        ... on GifContent { gifID: id gifURL: url }
      }
    }
  }
  parentMessage {
    id
    content {
      text
      fragments {
        text
        content {
          __typename
          ... on Emote { emoteID: id }
          ... on GifContent { gifID: id gifURL: url }
        }
      }
    }
    sender { id login displayName }
  }
  threadParentMessage {
    id
    sender { login }
  }
}
